${BEEZIP_SRC_DIR}/test/beezip_sim.sv
${BEEZIP_SRC_DIR}/main/parameters.vh
${BEEZIP_SRC_DIR}/main/log.vh
${BEEZIP_SRC_DIR}/main/common/pingpong_reg.v
${BEEZIP_SRC_DIR}/main/common/forward_reg.v
${BEEZIP_SRC_DIR}/main/common/fifo.v
${BEEZIP_SRC_DIR}/main/common/sram_1r1w.v
${BEEZIP_SRC_DIR}/main/common/unaligned_mem.v

${BEEZIP_SRC_DIR}/main/common/dff.v
${BEEZIP_SRC_DIR}/main/common/pop_count.v
${BEEZIP_SRC_DIR}/main/common/priority_encoder.v

${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/hash_row_synchronizer.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/post_hash_pe_scheduler.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/reorder_crossbar.v
${BEEZIP_SRC_DIR}/main/hash_engine/pre_hash_pe_scheduler/hash_pe_request_serializer.v
${BEEZIP_SRC_DIR}/main/hash_engine/pre_hash_pe_scheduler/pre_hash_pe_scheduler.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_compute.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_engine_top.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_pe_array.v
${BEEZIP_SRC_DIR}/main/hash_engine/input_leftover_buffer.v
${BEEZIP_SRC_DIR}/main/match_engine/input_data_hash_result_sync.v
${BEEZIP_SRC_DIR}/main/match_engine/job_dispatcher.v
${BEEZIP_SRC_DIR}/main/match_engine/match_pe.v
${BEEZIP_SRC_DIR}/main/match_engine/intra_pe_coordinator.v
${BEEZIP_SRC_DIR}/main/match_engine/switch_network.v
${BEEZIP_SRC_DIR}/main/match_engine/match_pu.v
${BEEZIP_SRC_DIR}/main/match_engine/match_pu_result_bus.v
${BEEZIP_SRC_DIR}/main/match_engine/window_buffer.v
${BEEZIP_SRC_DIR}/main/match_engine/job_seq_pack.v
${BEEZIP_SRC_DIR}/main/match_engine/job_collector.v
${BEEZIP_SRC_DIR}/main/match_engine/job_concat.v
${BEEZIP_SRC_DIR}/main/match_engine/match_engine_top.v
${BEEZIP_SRC_DIR}/main/beezip.v