-I${BEEZIP_SRC_DIR}/src/main
${BEEZIP_SRC_DIR}/main/beezip.v
${BEEZIP_SRC_DIR}/main/common/fifo.v
${BEEZIP_SRC_DIR}/main/common/dff.v
${BEEZIP_SRC_DIR}/main/common/forward_reg.v
${BEEZIP_SRC_DIR}/main/common/pingpong_reg.v
${BEEZIP_SRC_DIR}/main/common/pop_count.v
${BEEZIP_SRC_DIR}/main/common/mux1h.v
${BEEZIP_SRC_DIR}/main/common/sram2p.v
${BEEZIP_SRC_DIR}/main/common/priority_encoder.v
${BEEZIP_SRC_DIR}/main/common/priority_selector.v
${BEEZIP_SRC_DIR}/main/common/match_len_encoder.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_engine.v
${BEEZIP_SRC_DIR}/main/hash_engine/input_leftover_buffer.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_compute.v
${BEEZIP_SRC_DIR}/main/hash_engine/hash_pe_array.v
${BEEZIP_SRC_DIR}/main/hash_engine/pre_hash_pe_scheduler/pre_hash_pe_scheduler.v
${BEEZIP_SRC_DIR}/main/hash_engine/pre_hash_pe_scheduler/hash_pe_request_serializer.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/post_hash_pe_scheduler.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/hash_row_merge.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/hash_row_synchronizer.v
${BEEZIP_SRC_DIR}/main/hash_engine/post_hash_pe_scheduler/reorder_crossbar.v
${BEEZIP_SRC_DIR}/main/match_engine/match_engine.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_router_cluster.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_router.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_quad_fifo.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_dual_fifo.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_adapter_shared_match_pe.v
${BEEZIP_SRC_DIR}/main/match_engine/match_pe.v
${BEEZIP_SRC_DIR}/main/match_engine/match_pe_pipeline.v
${BEEZIP_SRC_DIR}/main/match_engine/window_buffer.v
${BEEZIP_SRC_DIR}/main/common/unaligned_mem.v
${BEEZIP_SRC_DIR}/main/match_engine/hash_batch_bus_node.v
${BEEZIP_SRC_DIR}/main/match_engine/seq_packet_bus_node.v
${BEEZIP_SRC_DIR}/main/match_engine/job_match_pe_cluster.v
${BEEZIP_SRC_DIR}/main/match_engine/shared_match_pe_cluster.v
${BEEZIP_SRC_DIR}/main/match_engine/job_pe.v
${BEEZIP_SRC_DIR}/main/match_engine/match_req_route_table.v
${BEEZIP_SRC_DIR}/main/match_engine/lazy_summary_pipeline.v
${BEEZIP_SRC_DIR}/main/match_engine/match_req_scheduler.v
${BEEZIP_SRC_DIR}/main/match_engine/match_resp_sync.v
${BEEZIP_SRC_DIR}/main/match_engine/mesh_adapter_job_pe.v
${BEEZIP_SRC_DIR}/main/match_engine/seq_packer.v
